### ISSUE TITLE
User registration fails with: Exception while invoking method 'subsidizeUser'

### ISSUE THREAD

**Issue by vjrj** [DemocracyEarth/sovereign#295]
# This is a Bug Report

#### :tophat: Description

For bug reports:
* What went wrong?
User registration fails with this trace:
```
I20180420-01:07:26.655(2)? Exception while invoking method 'subsidizeUser' { stack: 'TypeError: Cannot read property \'tally\' of undefined\n    at _updateTally (imports/api/transactions/transaction.js:577:16)\n    at _transact (imports/api/transactions/transaction.js:686:7)\n    at _genesisTransaction (imports/api/transactions/transaction.js:715:3)\n    at MethodInvocation.subsidizeUser (imports/api/server/methods.js:29:5)\n    at MethodInvocation.methodMap.(anonymous function) (packages/mdg_meteor-apm-agent.js:2729:30)\n    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1768:12)\n    at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:719:19)\n    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:12)\n    at DDPServer._CurrentWriteFence.withValue (packages/ddp-server/livedata_server.js:717:46)\n    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:12)\n    at Promise (packages/ddp-server/livedata_server.js:715:46)\n    at new Promise (<anonymous>)\n    at Session.method (packages/ddp-server/livedata_server.js:689:23)\n    at packages/mdg_meteor-apm-agent.js:2617:38\n    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:12)\n    at Session.sessionProto.protocol_handlers.method (packages/mdg_meteor-apm-agent.js:2616:44)\n    at packages/ddp-server/livedata_server.js:559:43',
```

More info here:
https://ci.comunes.org/job/sovereign/93/console

**Comment by vjrj** [comment]
I this this is solved by this recent commit by @santisiri: https://github.com/DemocracyEarth/sovereign/commit/281998108f17d05ec819d46d01805b671efe9174

**Comment by vjrj** [comment]
Grrrrr. Still fails:
https://ci.comunes.org/job/sovereign/162/console
