### ISSUE TITLE
TypeError: Cannot read property 'targetId' of undefined

### ISSUE THREAD

**Issue by vjrj** [DemocracyEarth/sovereign#334]
More info:
https://sentry.comunes.org/democracy-earth/votest-democracy-earth/issues/761/

```
TypeError: Cannot read property 'targetId' of undefined
  at targetId (meteor://💻app/imports/ui/templates/components/decision/fork/fork.js:212:89)
  at None (/packages/blaze.js:3775:20)
  at Function.Template._withTemplateInstanceFunc (/packages/blaze.js:3744:12)
  at Blaze.View.<anonymous> (/packages/blaze.js:3774:25)
  at None (/packages/blaze.js:2617:30)
...
(6 additional frame(s) were not displayed)
```

**Comment by vjrj** [comment]
More related errors:

https://sentry.comunes.org/democracy-earth/votest-democracy-earth/issues/745/
