### ISSUE TITLE
TypeError: Cannot read property 'active' of undefined

### ISSUE THREAD

**Issue by medied** [DemocracyEarth/sovereign#397]
https://sentry.comunes.org/democracy-earth/vote-democracy-earth/issues/957/

```
TypeError: Cannot read property 'active' of undefined
  at _validateEmail (/app.js:21697:54)
  at Signup.handleBlur (/app.js:9390:30)
  at Object.invokeGuardedCallback (/packages/modules.js:118397:5)
  at executeDispatch (/packages/modules.js:118223:21)
  at Object.executeDispatchesInOrder (/packages/modules.js:118246:5)
...
(13 additional frame(s) were not displayed)
```

**Comment by medied** [comment]
Resolved with 9fbaba361745b34723d54102e5419e88066a8a20
