### ISSUE TITLE
Error: EPERM: operation not permitted, stat 

### ISSUE THREAD

**Issue by indiofran** [DemocracyEarth/sovereign#406]
Specs:

- Windows 10

- Node 8.9.1

- Democracy Earth v1.1.1-alpha

I'am trying to run democracy earth in local computer, but i have this error.

I cloned the repository, run `meteor npm install` then ` meteor npm run start:dev` and them...
```
W20180919-11:59:09.526(-3)? (STDERR) C:\laragon\www\BANCA 61\intento 3\.meteor\local\build\programs\server\boot.js:475
W20180919-11:59:10.440(-3)? (STDERR) }).run();
W20180919-11:59:10.441(-3)? (STDERR)    ^
W20180919-11:59:10.441(-3)? (STDERR)
W20180919-11:59:10.442(-3)? (STDERR) Error: EPERM: operation not permitted, stat 'C:\laragon\www\BANCA 61\intento 3\.meteor\local\build\programs\server\node_modules'
W20180919-11:59:10.443(-3)? (STDERR)     at Object.realpathSync (fs.js:1678:17)
W20180919-11:59:10.444(-3)? (STDERR)     at toRealPath (module.js:164:13)
W20180919-11:59:10.444(-3)? (STDERR)     at tryFile (module.js:160:22)
W20180919-11:59:10.445(-3)? (STDERR)     at tryExtensions (module.js:172:22)
W20180919-11:59:10.446(-3)? (STDERR)     at Function.Module._findPath (module.js:225:20)
W20180919-11:59:10.447(-3)? (STDERR)     at Function.Module._resolveFilename (module.js:545:25)
W20180919-11:59:10.452(-3)? (STDERR)     at Function.Module._load (module.js:474:25)
W20180919-11:59:10.456(-3)? (STDERR)     at Module.require (module.js:596:17)
W20180919-11:59:10.459(-3)? (STDERR)     at require (internal/module.js:11:18)
W20180919-11:59:10.462(-3)? (STDERR)     at Object.require (C:\laragon\www\BANCA 61\intento 3\.meteor\local\build\programs\server\boot.js:284:20)
```

Thanks for the help.

**Comment by indiofran** [comment]
It solved, i update meteor, run `npm install` then because an error whit bluebird, i install fiber. Then start to work. Thanks
