### ISSUE TITLE
Currency is required [400] while creating user

### ISSUE THREAD

**Issue by zzvara** [DemocracyEarth/sovereign#484]
# This is a Bug Report

#### :tophat: Description

For bug reports:
* What went wrong?
User creation failed after first start in `dev` mode.
* What did you expect should have happened?
User can register.
* What was the config you used?
Default config from `master` branch from the time of this writing.
* What stacktrace or error message from your provider did you see?
```
Exception while invoking method 'createUser' { [object Object]
I20191202-19:56:57.849(1)?   invalidKeys:
I20191202-19:56:57.868(1)?    [ { name: 'profile.wallet.currency',
I20191202-19:56:57.881(1)?        type: 'required',
I20191202-19:56:57.897(1)?        value: null } ],
I20191202-19:56:57.902(1)?   validationContext:
I20191202-19:56:57.915(1)?    SimpleSchemaValidationContext {
I20191202-19:56:57.917(1)?      _simpleSchema:
I20191202-19:56:57.933(1)?       Where {
I20191202-19:56:57.947(1)?         _schema: [Object],
I20191202-19:56:57.951(1)?         _schemaKeys: [Array],
I20191202-19:56:57.964(1)?         _autoValues: [Object],
I20191202-19:56:57.968(1)?         _blackboxKeys: [Array],
I20191202-19:56:57.982(1)?         _validators: [Array],
I20191202-19:56:57.985(1)?         _messages: {},
I20191202-19:56:57.998(1)?         _depsMessages: [Object],
I20191202-19:56:58.001(1)?         _depsLabels: [Object],
I20191202-19:56:58.014(1)?         _firstLevelSchemaKeys: [Array],
I20191202-19:56:58.018(1)?         _objectKeys: [Object],
I20191202-19:56:58.029(1)?         _validationContexts: [Object] },
I20191202-19:56:58.051(1)?      _schema:
I20191202-19:56:58.066(1)?       { username: [Object],
I20191202-19:56:58.081(1)?         emails: [Object],
I20191202-19:56:58.084(1)?         'emails.$': [Object],
I20191202-19:56:58.098(1)?         'emails.$.address': [Object],
I20191202-19:56:58.101(1)?         'emails.$.verified': [Object],
I20191202-19:56:58.114(1)?         registered_emails: [Object],
I20191202-19:56:58.131(1)?         createdAt: [Object],
I20191202-19:56:58.135(1)?         profile: [Object],
I20191202-19:56:58.136(1)?         services: [Object],
I20191202-19:56:58.153(1)?         roles: [Object],
I20191202-19:56:58.164(1)?         heartbeat: [Object],
I20191202-19:56:58.167(1)?         'profile.firstName': [Object],
I20191202-19:56:58.181(1)?         'profile.lastName': [Object],
I20191202-19:56:58.185(1)?         'profile.picture': [Object],
I20191202-19:56:58.198(1)?         'profile.country': [Object],
I20191202-19:56:58.201(1)?         'profile.birthday': [Object],
I20191202-19:56:58.214(1)?         'profile.gender': [Object],
I20191202-19:56:58.217(1)?         'profile.organization': [Object],
I20191202-19:56:58.232(1)?         'profile.website': [Object],
I20191202-19:56:58.235(1)?         'profile.bio': [Object],
I20191202-19:56:58.248(1)?         'profile.configured': [Object],
I20191202-19:56:58.251(1)?         'profile.credentials': [Object],
I20191202-19:56:58.266(1)?         'profile.credentials.$': [Object],
I20191202-19:56:58.280(1)?         'profile.url': [Object],
I20191202-19:56:58.283(1)?         'profile.menu': [Object],
I20191202-19:56:58.296(1)?         'profile.menu.$': [Object],
I20191202-19:56:58.299(1)?         'profile.wallet': [Object],
I20191202-19:56:58.314(1)?         'profile.settings': [Object],
I20191202-19:56:58.317(1)?         'profile.delegations': [Object],
I20191202-19:56:58.330(1)?         'profile.country.name': [Object],
I20191202-19:56:58.334(1)?         'profile.country.code': [Object],
I20191202-19:56:58.349(1)?         'profile.credentials.$.source': [Object],
I20191202-19:56:58.352(1)?         'profile.credentials.$.URL': [Object],
I20191202-19:56:58.365(1)?         'profile.credentials.$.validated': [Object],
I20191202-19:56:58.368(1)?         'profile.menu.$.feed': [Object],
I20191202-19:56:58.369(1)?         'profile.menu.$.lastView': [Object],
I20191202-19:56:58.386(1)?         'profile.menu.$.newItems': [Object],
I20191202-19:56:58.401(1)?         'profile.wallet.balance': [Object],
I20191202-19:56:58.415(1)?         'profile.wallet.placed': [Object],
I20191202-19:56:58.417(1)?         'profile.wallet.available': [Object],
I20191202-19:56:58.430(1)?         'profile.wallet.currency': [Object],
I20191202-19:56:58.433(1)?         'profile.wallet.reserves': [Object],
I20191202-19:56:58.448(1)?         'profile.wallet.address': [Object],
I20191202-19:56:58.451(1)?         'profile.wallet.address.$': [Object],
I20191202-19:56:58.476(1)?         'profile.wallet.address.$.hash': [Object],
I20191202-19:56:58.480(1)?         'profile.wallet.address.$.collectiveId': [Object],
I20191202-19:56:58.493(1)?         'profile.wallet.ledger': [Object],
I20191202-19:56:58.496(1)?         'profile.wallet.ledger.$': [Object],
I20191202-19:56:58.511(1)?         'profile.wallet.ledger.$.txId': [Object],
I20191202-19:56:58.514(1)?         'profile.wallet.ledger.$.quantity': [Object],
I20191202-19:56:58.527(1)?         'profile.wallet.ledger.$.entityId': [Object],
I20191202-19:56:58.530(1)?         'profile.wallet.ledger.$.entityType': [Object],
I20191202-19:56:58.547(1)?         'profile.wallet.ledger.$.currency': [Object],
I20191202-19:56:58.550(1)?         'profile.wallet.ledger.$.transactionType': [Object],
I20191202-19:56:58.563(1)?         'profile.wallet.ledger.$.ballot': [Object],
I20191202-19:56:58.566(1)?         'profile.wallet.ledger.$.ballot.$': [Object],
I20191202-19:56:58.581(1)?         'profile.wallet.reserves.$.publicAddress': [Object],
I20191202-19:56:58.584(1)?         'profile.wallet.reserves.$.token': [Object],
I20191202-19:56:58.598(1)?         'profile.wallet.reserves.$.balance': [Object],
I20191202-19:56:58.600(1)?         'profile.wallet.reserves.$.placed': [Object],
I20191202-19:56:58.613(1)?         'profile.wallet.reserves.$.available': [Object],
I20191202-19:56:58.616(1)?         'profile.wallet.ledger.$.ballot.$._id': [Object],
I20191202-19:56:58.629(1)?         'profile.wallet.ledger.$.ballot.$.mode': [Object],
I20191202-19:56:58.632(1)?         'profile.wallet.ledger.$.ballot.$.rank': [Object],
I20191202-19:56:58.646(1)?         'profile.wallet.ledger.$.ballot.$.url': [Object],
I20191202-19:56:58.649(1)?         'profile.wallet.ledger.$.ballot.$.label': [Object],
I20191202-19:56:58.665(1)?         'profile.wallet.ledger.$.ballot.$.executive': [Object],
I20191202-19:56:58.668(1)?         'profile.wallet.ledger.$.ballot.$.tick': [Object],
I20191202-19:56:58.681(1)?         'profile.wallet.reserves.$': [Object],
I20191202-19:56:58.684(1)?         'profile.settings.splitLeftWidth': [Object],
I20191202-19:56:58.697(1)?         'profile.settings.splitRightWidth': [Object],
I20191202-19:56:58.700(1)?         'profile.delegations.$.userId': [Object],
I20191202-19:56:58.715(1)?         'profile.delegations.$.policies': [Object],
I20191202-19:56:58.718(1)?         'profile.delegations.$.tickets': [Object],
I20191202-19:56:58.731(1)?         'profile.delegations.$.policies.$.contractId': [Object],
I20191202-19:56:58.734(1)?         'profile.delegations.$.policies.$.incoming': [Object],
I20191202-19:56:58.749(1)?         'profile.delegations.$.tickets.$.hash': [Object],
I20191202-19:56:58.751(1)?         'profile.delegations.$.tickets.$.status': [Object],
I20191202-19:56:58.752(1)?         'profile.delegations.$.tickets.$.value': [Object],
I20191202-19:56:58.768(1)?         'profile.delegations.$.policies.$': [Object],
I20191202-19:56:58.781(1)?         'profile.delegations.$.tickets.$': [Object],
I20191202-19:56:58.784(1)?         'profile.delegations.$': [Object],
I20191202-19:56:58.798(1)?         'registered_emails.$': [Object] },
I20191202-19:56:58.800(1)?      _schemaKeys:
I20191202-19:56:58.814(1)?       [ 'username',
I20191202-19:56:58.817(1)?         'emails',
I20191202-19:56:58.831(1)?         'emails.$',
I20191202-19:56:58.834(1)?         'emails.$.address',
I20191202-19:56:58.847(1)?         'emails.$.verified',
I20191202-19:56:58.850(1)?         'registered_emails',
I20191202-19:56:58.865(1)?         'createdAt',
I20191202-19:56:58.868(1)?         'profile',
I20191202-19:56:58.880(1)?         'services',
I20191202-19:56:58.883(1)?         'roles',
I20191202-19:56:58.899(1)?         'heartbeat',
I20191202-19:56:58.901(1)?         'profile.firstName',
I20191202-19:56:58.913(1)?         'profile.lastName',
I20191202-19:56:58.916(1)?         'profile.picture',
I20191202-19:56:58.917(1)?         'profile.country',
I20191202-19:56:58.932(1)?         'profile.birthday',
I20191202-19:56:58.932(1)?         'profile.gender',
I20191202-19:56:58.945(1)?         'profile.organization',
I20191202-19:56:58.948(1)?         'profile.website',
I20191202-19:56:58.962(1)?         'profile.bio',
I20191202-19:56:58.965(1)?         'profile.configured',
I20191202-19:56:58.979(1)?         'profile.credentials',
I20191202-19:56:58.982(1)?         'profile.credentials.$',
I20191202-19:56:58.997(1)?         'profile.url',
I20191202-19:56:58.998(1)?         'profile.menu',
I20191202-19:56:59.011(1)?         'profile.menu.$',
I20191202-19:56:59.013(1)?         'profile.wallet',
I20191202-19:56:59.028(1)?         'profile.settings',
I20191202-19:56:59.029(1)?         'profile.delegations',
I20191202-19:56:59.046(1)?         'profile.country.name',
I20191202-19:56:59.048(1)?         'profile.country.code',
I20191202-19:56:59.065(1)?         'profile.credentials.$.source',
I20191202-19:56:59.067(1)?         'profile.credentials.$.URL',
I20191202-19:56:59.091(1)?         'profile.credentials.$.validated',
I20191202-19:56:59.095(1)?         'profile.menu.$.feed',
I20191202-19:56:59.096(1)?         'profile.menu.$.lastView',
I20191202-19:56:59.111(1)?         'profile.menu.$.newItems',
I20191202-19:56:59.123(1)?         'profile.wallet.balance',
I20191202-19:56:59.125(1)?         'profile.wallet.placed',
I20191202-19:56:59.126(1)?         'profile.wallet.available',
I20191202-19:56:59.141(1)?         'profile.wallet.currency',
I20191202-19:56:59.151(1)?         'profile.wallet.reserves',
I20191202-19:56:59.165(1)?         'profile.wallet.address',
I20191202-19:56:59.167(1)?         'profile.wallet.address.$',
I20191202-19:56:59.182(1)?         'profile.wallet.address.$.hash',
I20191202-19:56:59.184(1)?         'profile.wallet.address.$.collectiveId',
I20191202-19:56:59.185(1)?         'profile.wallet.ledger',
I20191202-19:56:59.200(1)?         'profile.wallet.ledger.$',
I20191202-19:56:59.213(1)?         'profile.wallet.ledger.$.txId',
I20191202-19:56:59.216(1)?         'profile.wallet.ledger.$.quantity',
I20191202-19:56:59.229(1)?         'profile.wallet.ledger.$.entityId',
I20191202-19:56:59.231(1)?         'profile.wallet.ledger.$.entityType',
I20191202-19:56:59.246(1)?         'profile.wallet.ledger.$.currency',
I20191202-19:56:59.249(1)?         'profile.wallet.ledger.$.transactionType',
I20191202-19:56:59.264(1)?         'profile.wallet.ledger.$.ballot',
I20191202-19:56:59.267(1)?         'profile.wallet.ledger.$.ballot.$',
I20191202-19:56:59.280(1)?         'profile.wallet.reserves.$.publicAddress',
I20191202-19:56:59.283(1)?         'profile.wallet.reserves.$.token',
I20191202-19:56:59.298(1)?         'profile.wallet.reserves.$.balance',
I20191202-19:56:59.300(1)?         'profile.wallet.reserves.$.placed',
I20191202-19:56:59.301(1)?         'profile.wallet.reserves.$.available',
I20191202-19:56:59.317(1)?         'profile.wallet.ledger.$.ballot.$._id',
I20191202-19:56:59.329(1)?         'profile.wallet.ledger.$.ballot.$.mode',
I20191202-19:56:59.332(1)?         'profile.wallet.ledger.$.ballot.$.rank',
I20191202-19:56:59.346(1)?         'profile.wallet.ledger.$.ballot.$.url',
I20191202-19:56:59.347(1)?         'profile.wallet.ledger.$.ballot.$.label',
I20191202-19:56:59.363(1)?         'profile.wallet.ledger.$.ballot.$.executive',
I20191202-19:56:59.366(1)?         'profile.wallet.ledger.$.ballot.$.tick',
I20191202-19:56:59.381(1)?         'profile.wallet.reserves.$',
I20191202-19:56:59.383(1)?         'profile.settings.splitLeftWidth',
I20191202-19:56:59.384(1)?         'profile.settings.splitRightWidth',
I20191202-19:56:59.400(1)?         'profile.delegations.$.userId',
I20191202-19:56:59.401(1)?         'profile.delegations.$.policies',
I20191202-19:56:59.414(1)?         'profile.delegations.$.tickets',
I20191202-19:56:59.416(1)?         'profile.delegations.$.policies.$.contractId',
I20191202-19:56:59.431(1)?         'profile.delegations.$.policies.$.incoming',
I20191202-19:56:59.434(1)?         'profile.delegations.$.tickets.$.hash',
I20191202-19:56:59.447(1)?         'profile.delegations.$.tickets.$.status',
I20191202-19:56:59.450(1)?         'profile.delegations.$.tickets.$.value',
I20191202-19:56:59.465(1)?         'profile.delegations.$.policies.$',
I20191202-19:56:59.468(1)?         'profile.delegations.$.tickets.$',
I20191202-19:56:59.481(1)?         'profile.delegations.$',
I20191202-19:56:59.483(1)?         'registered_emails.$' ],
I20191202-19:56:59.498(1)?      _invalidKeys: [ [Object] ],
I20191202-19:56:59.501(1)?      _deps:
I20191202-19:56:59.515(1)?       { username: [Object],
I20191202-19:56:59.517(1)?         emails: [Object],
I20191202-19:56:59.533(1)?         'emails.$': [Object],
I20191202-19:56:59.535(1)?         'emails.$.address': [Object],
I20191202-19:56:59.548(1)?         'emails.$.verified': [Object],
I20191202-19:56:59.551(1)?         registered_emails: [Object],
I20191202-19:56:59.566(1)?         createdAt: [Object],
I20191202-19:56:59.569(1)?         profile: [Object],
I20191202-19:56:59.583(1)?         services: [Object],
I20191202-19:56:59.599(1)?         roles: [Object],
I20191202-19:56:59.601(1)?         heartbeat: [Object],
I20191202-19:56:59.614(1)?         'profile.firstName': [Object],
I20191202-19:56:59.616(1)?         'profile.lastName': [Object],
I20191202-19:56:59.632(1)?         'profile.picture': [Object],
I20191202-19:56:59.634(1)?         'profile.country': [Object],
I20191202-19:56:59.647(1)?         'profile.birthday': [Object],
I20191202-19:56:59.650(1)?         'profile.gender': [Object],
I20191202-19:56:59.664(1)?         'profile.organization': [Object],
I20191202-19:56:59.667(1)?         'profile.website': [Object],
I20191202-19:56:59.680(1)?         'profile.bio': [Object],
I20191202-19:56:59.682(1)?         'profile.configured': [Object],
I20191202-19:56:59.698(1)?         'profile.credentials': [Object],
I20191202-19:56:59.701(1)?         'profile.credentials.$': [Object],
I20191202-19:56:59.713(1)?         'profile.url': [Object],
I20191202-19:56:59.716(1)?         'profile.menu': [Object],
I20191202-19:56:59.729(1)?         'profile.menu.$': [Object],
I20191202-19:56:59.746(1)?         'profile.wallet': [Object],
I20191202-19:56:59.750(1)?         'profile.settings': [Object],
I20191202-19:56:59.766(1)?         'profile.delegations': [Object],
I20191202-19:56:59.768(1)?         'profile.country.name': [Object],
I20191202-19:56:59.783(1)?         'profile.country.code': [Object],
I20191202-19:56:59.797(1)?         'profile.credentials.$.source': [Object],
I20191202-19:56:59.800(1)?         'profile.credentials.$.URL': [Object],
I20191202-19:56:59.813(1)?         'profile.credentials.$.validated': [Object],
I20191202-19:56:59.816(1)?         'profile.menu.$.feed': [Object],
I20191202-19:56:59.829(1)?         'profile.menu.$.lastView': [Object],
I20191202-19:56:59.832(1)?         'profile.menu.$.newItems': [Object],
I20191202-19:56:59.847(1)?         'profile.wallet.balance': [Object],
I20191202-19:56:59.850(1)?         'profile.wallet.placed': [Object],
I20191202-19:56:59.864(1)?         'profile.wallet.available': [Object],
I20191202-19:56:59.867(1)?         'profile.wallet.currency': [Object],
I20191202-19:56:59.880(1)?         'profile.wallet.reserves': [Object],
I20191202-19:56:59.883(1)?         'profile.wallet.address': [Object],
I20191202-19:56:59.897(1)?         'profile.wallet.address.$': [Object],
I20191202-19:56:59.900(1)?         'profile.wallet.address.$.hash': [Object],
I20191202-19:56:59.913(1)?         'profile.wallet.address.$.collectiveId': [Object],
I20191202-19:56:59.916(1)?         'profile.wallet.ledger': [Object],
I20191202-19:56:59.929(1)?         'profile.wallet.ledger.$': [Object],
I20191202-19:56:59.932(1)?         'profile.wallet.ledger.$.txId': [Object],
I20191202-19:56:59.944(1)?         'profile.wallet.ledger.$.quantity': [Object],
I20191202-19:56:59.947(1)?         'profile.wallet.ledger.$.entityId': [Object],
I20191202-19:56:59.960(1)?         'profile.wallet.ledger.$.entityType': [Object],
I20191202-19:56:59.964(1)?         'profile.wallet.ledger.$.currency': [Object],
I20191202-19:56:59.978(1)?         'profile.wallet.ledger.$.transactionType': [Object],
I20191202-19:56:59.980(1)?         'profile.wallet.ledger.$.ballot': [Object],
I20191202-19:56:59.993(1)?         'profile.wallet.ledger.$.ballot.$': [Object],
I20191202-19:56:59.996(1)?         'profile.wallet.reserves.$.publicAddress': [Object],
I20191202-19:57:00.009(1)?         'profile.wallet.reserves.$.token': [Object],
I20191202-19:57:00.011(1)?         'profile.wallet.reserves.$.balance': [Object],
I20191202-19:57:00.026(1)?         'profile.wallet.reserves.$.placed': [Object],
I20191202-19:57:00.029(1)?         'profile.wallet.reserves.$.available': [Object],
I20191202-19:57:00.043(1)?         'profile.wallet.ledger.$.ballot.$._id': [Object],
I20191202-19:57:00.046(1)?         'profile.wallet.ledger.$.ballot.$.mode': [Object],
I20191202-19:57:00.060(1)?         'profile.wallet.ledger.$.ballot.$.rank': [Object],
I20191202-19:57:00.063(1)?         'profile.wallet.ledger.$.ballot.$.url': [Object],
I20191202-19:57:00.076(1)?         'profile.wallet.ledger.$.ballot.$.label': [Object],
I20191202-19:57:00.079(1)?         'profile.wallet.ledger.$.ballot.$.executive': [Object],
I20191202-19:57:00.080(1)?         'profile.wallet.ledger.$.ballot.$.tick': [Object],
I20191202-19:57:00.093(1)?         'profile.wallet.reserves.$': [Object],
I20191202-19:57:00.097(1)?         'profile.settings.splitLeftWidth': [Object],
I20191202-19:57:00.109(1)?         'profile.settings.splitRightWidth': [Object],
I20191202-19:57:00.112(1)?         'profile.delegations.$.userId': [Object],
I20191202-19:57:00.125(1)?         'profile.delegations.$.policies': [Object],
I20191202-19:57:00.128(1)?         'profile.delegations.$.tickets': [Object],
I20191202-19:57:00.140(1)?         'profile.delegations.$.policies.$.contractId': [Object],
I20191202-19:57:00.143(1)?         'profile.delegations.$.policies.$.incoming': [Object],
I20191202-19:57:00.156(1)?         'profile.delegations.$.tickets.$.hash': [Object],
I20191202-19:57:00.160(1)?         'profile.delegations.$.tickets.$.status': [Object],
I20191202-19:57:00.173(1)?         'profile.delegations.$.tickets.$.value': [Object],
I20191202-19:57:00.176(1)?         'profile.delegations.$.policies.$': [Object],
I20191202-19:57:00.189(1)?         'profile.delegations.$.tickets.$': [Object],
I20191202-19:57:00.192(1)?         'profile.delegations.$': [Object],
I20191202-19:57:00.202(1)?         'registered_emails.$': [Object] },
I20191202-19:57:00.206(1)?      _depsAny: Dependency { _dependentsById: {} } },
I20191202-19:57:00.217(1)?   sanitizedError:
I20191202-19:57:00.232(1)?    { Error: Currency is required [400]
I20191202-19:57:00.234(1)?     at getErrorObject (packages\aldeed_collection2-core.js:486:28)
I20191202-19:57:00.249(1)?     at Collection.doValidate (packages\aldeed_collection2-core.js:462:13)
I20191202-19:57:00.252(1)?     at Collection.Mongo.Collection.(anonymous function) [as insert] (packages\aldeed_collection2-core.js:214:25)
I20191202-19:57:00.267(1)?     at AccountsServer.insertUserDoc (packages/accounts-base/accounts_server.js:1100:27)
I20191202-19:57:00.281(1)?     at createUser (packages/accounts-password/password_server.js:1078:25)
I20191202-19:57:00.284(1)?     at packages/accounts-password/password_server.js:1109:20
I20191202-19:57:00.298(1)?     at tryLoginMethod (packages/accounts-base/accounts_server.js:1294:14)
I20191202-19:57:00.314(1)?     at AccountsServer._loginMethod (packages/accounts-base/accounts_server.js:374:7)
I20191202-19:57:00.318(1)?     at MethodInvocation.createUser (packages/accounts-password/password_server.js:1095:19)
I20191202-19:57:00.333(1)?     at MethodInvocation.methodMap.(anonymous function) (packages/mdg:meteor-apm-agent/lib/hijack/wrap_session.js:161:30)
I20191202-19:57:00.334(1)?     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)
I20191202-19:57:00.335(1)?     at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:719:19)
I20191202-19:57:00.348(1)?     at Meteor.EnvironmentVariable.EVp.withValue (packages\meteor.js:1234:12)
I20191202-19:57:00.352(1)?     at DDPServer._CurrentWriteFence.withValue (packages/ddp-server/livedata_server.js:717:46)
I20191202-19:57:00.366(1)?     at Meteor.EnvironmentVariable.EVp.withValue (packages\meteor.js:1234:12)
I20191202-19:57:00.379(1)?     at Promise (packages/ddp-server/livedata_server.js:715:46)
I20191202-19:57:00.383(1)?     at new Promise (<anonymous>)
I20191202-19:57:00.404(1)?     at Session.method (packages/ddp-server/livedata_server.js:689:23)
I20191202-19:57:00.414(1)?     at packages/mdg:meteor-apm-agent/lib/hijack/wrap_session.js:52:38
I20191202-19:57:00.417(1)?     at Meteor.EnvironmentVariable.EVp.withValue (packages\meteor.js:1234:12)
I20191202-19:57:00.430(1)?     at Session.sessionProto.protocol_handlers.method (packages/mdg:meteor-apm-agent/lib/hijack/wrap_session.js:51:44)
I20191202-19:57:00.433(1)?     at packages/ddp-server/livedata_server.js:559:43
I20191202-19:57:00.448(1)?      isClientSafe: true,
I20191202-19:57:00.451(1)?      error: 400,
I20191202-19:57:00.465(1)?      reason: 'Currency is required',
I20191202-19:57:00.467(1)?      details: '[{"name":"profile.wallet.currency","type":"required","value":null}]',
I20191202-19:57:00.481(1)?      message: 'Currency is required [400]',
I20191202-19:57:00.483(1)?      errorType: 'Meteor.Error' } }
I20191202-19:57:00.543(1)? Sanitized and reported to the client as: { Error: Currency is required [400]
I20191202-19:57:00.546(1)?     at getErrorObject (packages\aldeed_collection2-core.js:486:28)
I20191202-19:57:00.548(1)?     at Collection.doValidate (packages\aldeed_collection2-core.js:462:13)
I20191202-19:57:00.548(1)?     at Collection.Mongo.Collection.(anonymous function) [as insert] (packages\aldeed_collection2-core.js:214:25)
I20191202-19:57:00.564(1)?     at AccountsServer.insertUserDoc (packages/accounts-base/accounts_server.js:1100:27)
I20191202-19:57:00.576(1)?     at createUser (packages/accounts-password/password_server.js:1078:25)
I20191202-19:57:00.580(1)?     at packages/accounts-password/password_server.js:1109:20
I20191202-19:57:00.598(1)?     at tryLoginMethod (packages/accounts-base/accounts_server.js:1294:14)
I20191202-19:57:00.602(1)?     at AccountsServer._loginMethod (packages/accounts-base/accounts_server.js:374:7)
I20191202-19:57:00.619(1)?     at MethodInvocation.createUser (packages/accounts-password/password_server.js:1095:19)
I20191202-19:57:00.625(1)?     at MethodInvocation.methodMap.(anonymous function) (packages/mdg:meteor-apm-agent/lib/hijack/wrap_session.js:161:30)
I20191202-19:57:00.638(1)?     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)
I20191202-19:57:00.642(1)?     at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:719:19)
I20191202-19:57:00.658(1)?     at Meteor.EnvironmentVariable.EVp.withValue (packages\meteor.js:1234:12)
I20191202-19:57:00.662(1)?     at DDPServer._CurrentWriteFence.withValue (packages/ddp-server/livedata_server.js:717:46)
I20191202-19:57:00.679(1)?     at Meteor.EnvironmentVariable.EVp.withValue (packages\meteor.js:1234:12)
I20191202-19:57:00.683(1)?     at Promise (packages/ddp-server/livedata_server.js:715:46)
I20191202-19:57:00.699(1)?     at new Promise (<anonymous>)
I20191202-19:57:00.716(1)?     at Session.method (packages/ddp-server/livedata_server.js:689:23)
I20191202-19:57:00.732(1)?     at packages/mdg:meteor-apm-agent/lib/hijack/wrap_session.js:52:38
I20191202-19:57:00.748(1)?     at Meteor.EnvironmentVariable.EVp.withValue (packages\meteor.js:1234:12)
I20191202-19:57:00.765(1)?     at Session.sessionProto.protocol_handlers.method (packages/mdg:meteor-apm-agent/lib/hijack/wrap_session.js:51:44)
I20191202-19:57:00.782(1)?     at packages/ddp-server/livedata_server.js:559:43
I20191202-19:57:00.799(1)?   isClientSafe: true,
I20191202-19:57:00.816(1)?   error: 400,
I20191202-19:57:00.832(1)?   reason: 'Currency is required',
I20191202-19:57:00.835(1)?   details: '[{"name":"profile.wallet.currency","type":"required","value":null}]',
I20191202-19:57:00.849(1)?   message: 'Currency is required [400]',
I20191202-19:57:00.863(1)?   errorType: 'Meteor.Error' }
```

#### :clipboard: Additional Data

* ***Sovereign deployment where you found the issue***: I think the https://democracy.earth/ has the same problem.
* ***Browser & version***:
* ***Screenshot***:
* ***Error messages***:
* ***URL to reproduce the error***:

**Comment by santisiri** [comment]
Look for `Schema.User` and there's probably a `currency` requirement there as an object. You are creating the object but somehow has a `value: null`

**Comment by santisiri** [comment]
Also, check the new release that now is 100% based on DAOs.. this one will be deployed soon to the main site but in the meantime you can play with it on [moloch.democracy.earth](https://moloch.democracy.earth)
