### ISSUE TITLE
Can't add Houston admin user

### ISSUE THREAD

**Issue by vicnicius** [DemocracyEarth/sovereign#57]
When trying to add a Houston admin user directly, I get this error: 

```
I20161119-21:04:18.837(-2)? [onCreateUser] no username is defined, generating a new one.
I20161119-21:04:19.684(-2)? Exception while invoking method 'createUser' { stack: 'TypeError: Cannot read property \'firstName\' of undefined\n    at AccountsServer._onCreateUserHook (imports/startup/server/accounts/accounts.js:59:37)\n    at AccountsServer.Ap.insertUserDoc (packages/accounts-base/accounts_server.js:1308:21)\n    at _createUser (packages/accounts-password/password_server.js:1009:25)\n    at packages/accounts-password/password_server.js:1040:20\n    at tryLoginMethod (packages/accounts-base/accounts_server.js:248:14)\n    at AccountsServer.Ap._loginMethod (packages/accounts-base/accounts_server.js:381:5)\n    at [object Object].createUser (packages/accounts-password/password_server.js:1026:19)\n    at [object Object].methodMap.(anonymous function) (packages/meteorhacks_kadira.js:2731:30)\n    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1711:12)\n    at packages/ddp-server/livedata_server.js:711:19',
I20161119-21:04:19.685(-2)?   source: 'method' }
```

I can clearly see what's causing the bug by looking at [the account module](https://github.com/DemocracyEarth/sovereign/blob/master/imports/startup/server/accounts/accounts.js) and would love to send a fix if that's ok.

**Comment by LucasIsasmendi** [comment]
Yes please, send it. 
This will be good test scenario.

**Comment by vicnicius** [comment]
Working on it! :smile:
